server:
  port: 8083

spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
          healthTimeout: 20
        bindings:
          input:
            destination: korello
            group: korello
            consumer:
              maxAttempts: 3
              backOffInitialInterval: 500
              backOffMaxInterval: 1000
              enableDlq: true

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: bindings
